on: [pull_request]

env:
  CARGO_TERM_COLOR: always

name: Test

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.76.0

      
      - name: Test
        run: |
          cd zokrates_stdlib
          cargo test